language: python
python:
- 3.6.9
install:
- python --version
- pip install pipenv
- pipenv install
script: pytest
deploy:
  provider: pypi
  user: __token__
  password:
    secure: MmQ3uDgrSv5M4Iku4hC5aoKGC20esZW/mZU55J+VT8o0MUgtL4zQmd1tae8MyuW+MPsQrVC+ixRL+jh5/Il/5+q7BOxtKHA4Kisq+BP0b98BktT6ENeJSOVIGHfxgYMvAOV4fzsxb+phlvKZOGw62PenAlxcB0i+a85ej/twInSH+8CI9qjtCYRowWsB1pXdKUI9vQW2rZH5pV9vgNuz4GqejwlxQeluZ4XoHzuIGMqA5XlJsXohIVmeLU193tsNw9U88bZs68hfnjgpDOBitnKwrVEMXl5JsBe8Z6NgjJqjXcsRxSAPlKa8Y4EKG1GLxbb/c1JqBD1DQ/vAG4pSlhw8lxMpuJNt7okvpo+84tzBPfS2enaKCF12GJO1jz/OQqirfhxtYAx8ueR4U+6RYLzk1HsnkBcyuAtI8kow26RXH15MrlHqbLniLurVtg0ZIUIFKx2wiyGrhZSulR/b5dk5dMSQy1djPuphZTWpumg2hNO8HZMapS8uBbgFxuHjqhtBbllyLQh4JSeMuxiUcPoqkuT+Obyyrcqp3wUPLGEuZmnkM8iw+vv8uZLTH5A8aIweWp/npwKu3xYs+1HaNDshZcxVAPSi5cmoRsy/LBsdcRElZz9765DCxK9hfOzd43RAg0h1zWvaYCqxaFwwpWouybQRXtIbrYgA3drYT08=
on:
  tags: true
on:
  branch: master
